services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: liniker123
      MYSQL_DATABASE: planets_explorer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/planets_explorer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: liniker123
    depends_on:
      db:
        condition: service_healthy
